# Generated by Django 4.0.2 on 2022-02-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='Timestamp',
            new_name='timestamp',
        ),
    ]
